# Generated by Django 4.2.3 on 2023-08-15 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstoremodel',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
